version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: sisqr6-postgres
    restart: unless-stopped
    environment:
      # Usar valores coherentes con el backend por defecto
      POSTGRES_DB: ${DB_NAME:-sisqr6}
      POSTGRES_USER: ${DB_USER:-sisqr6_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Scripts SQL para inicialización automática (se ejecutan solo si el volumen está vacío)
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - sisqr6-network
    healthcheck:
      # Comprobar disponibilidad usando el usuario configurado
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-sisqr6_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sisqr6-backend
    restart: unless-stopped
    ports:
      - "3001:3000"  # Puerto externo 3001 mapeado al interno 3000
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-sisqr6}
      DB_USER: ${DB_USER:-sisqr6_user}
      DB_PASSWORD: ${DB_PASSWORD:-postgres123}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      FRONTEND_URL: ${FRONTEND_URL:-https://localhost}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sisqr6-network
    volumes:
      - backend_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sisqr6-frontend
    restart: unless-stopped
    ports:
      - "8080:80"  # Puerto externo 8080 mapeado al interno 80
    depends_on:
      - backend
    networks:
      - sisqr6-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sisqr6-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local
